apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: "root"
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: "pass12345"
          volumeMounts:
            - mountPath: /data/db
              name: mongodb-storage
            - mountPath: /docker-entrypoint-initdb.d/mongo-init.js
              subPath: mongo-init.js
              name: mongo-init-script
      volumes:
        - name: mongodb-storage
          persistentVolumeClaim:
            claimName: mongodb-pvc
        - name: mongo-init-script
          configMap:
            name: mongo-init-script
