apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: myapp-service
  labels:
    app: myapp
spec:
  selector:
    app: myapp
  ports:
    - protocol: TCP
      port: 80F
      targetPort: 8081
      nodePort: 30081  # Change this to any value within the range 30000-32767
  type: NodePort
