spring:
  profiles:
    active: prd
  data:
    mongodb:
      repositories:
        enabled: true
      uri: mongodb://root:pass12345@mongodb-service.default.svc.cluster.local:27017/messages?authSource=admin
      database: messages
      authentication-database: admin
  kafka:
    msg:
      bootstrap-servers: ${KAFKA_RESERVATION_BOOTSTRAP_SERVERS:kafka-service:9092}
      topic:
        vovk: vovk
      consumer:
        group-id:
          notification: notification
          service: service
logging:
  level:
    org.springframework.boot.context.properties: DEBUG